version: "3.7"
services:
  opensearch:
    image: stratcomms.common.infopc.net/base/opensearchproject/opensearch:2.8.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_master_nodes=opensearch
      - plugins.query.datasources.encryption.masterkey=b534b1ce4f4f04b524a2b500
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    ports:
      - 9276:9200
      - 9277:9600 # required for Performance Analyzer
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    networks:
      - host-net

  opensearch-dashboards:
    image: stratcomms.common.infopc.net/base/opensearchproject/opensearch-dashboards:2.8.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - host-net

  vector:
    image: timberio/vector:nightly-2024-02-14-alpine
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector.yaml:/etc/vector/vector.yaml
    networks:
      - host-net

  prometheus:
    image: rapidfort/prometheus:latest
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - host-net

  node-exporter:
    image: rapidfort/node-exporter:1.7-debian-11
    networks:
      - host-net
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana-enterprise:latest
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_FEATURE_TOGGLES_ENABLE: "timeSeriesTable"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./setup:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - host-net

  tempo:
    image: grafana/tempo:main-24cbe3e
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    container_name: tempo
    hostname: tempo
    #      command: [ "-config.file=/etc/tempo.yaml", "-multitenancy.enabled=true"]
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    networks:
      - host-net

  loki:
    image: grafana/loki:main
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    container_name: loki
    hostname: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command:
      ["-config.file=/etc/loki/local-config.yaml", "-config.expand-env=true"]
    networks:
      - host-net

  promtail:
    image: grafana/promtail:main
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - host-net

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    hostname: otel_collector
    container_name: otel_collector
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./otel-collector-config.yaml:/conf/config.yaml
    restart: on-failure
    ports:
      - 8889:8889
    networks:
      - host-net
networks:
  host-net:
    external: true
