global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: opensearch
    metrics_path: "/_prometheus/metrics"
    scheme: https
    basic_auth:
      username: admin
      password: admin
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["opensearch:9200"]
  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000
  - job_name: opentelemetry_metrics
    static_configs:
      - targets: ["otel_collector:8889"]