version: '3.7'

services:
    common-apps-api-server:
        image: driver-app:1.0.0
        container_name: common-apps-api-server
        labels:
            product: 'common-apps'
            app: 'search'
        environment:
            - SERVER_PORT=5055
        ports:
            - 5055:5055
        networks:
            - host-net
        logging: &logging
            driver: fluentd
            options:
                fluentd-address: localhost:8086

    folders-api-server:
        image: driver-app:1.0.0
        container_name: folders-api-server
        labels:
            product: 'folders'
            app: 'scan'
        environment:
            - SERVER_PORT=5056
        ports:
            - 5056:5056
        networks:
            - host-net
        logging: *logging

networks:
    host-net:
        external: true
