# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

ENABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS

CLEAR_REPORT_FOLDER: true
DOCKERFILE_HADOLINT_ARGUMENTS: "-t error"
FILEIO_REPORTER: false
GITLAB_COMMENT_REPORTER: false
OUTPUT_DETAIL: detailed
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
