version: '3.7'

services:
    common-apps-api-server:
        image: driver-app:1.0.0
        container_name: common-apps-api-server
        labels:
            product: 'common-apps'
            app: 'search'
        environment:
            - SERVER_PORT=5055
            - OTEL_COLLECTOR_HOST=http://alloy:4318
            - OTEL_SERVICE_NAMESPACE=common-apps
            - OTEL_SERVICE_NAME=search
            - OTEL_SERVICE_VERSION=1.0.0
        ports:
            - 5055:5055
        networks:
            - host-net

    folders-api-server:
        image: driver-app:1.0.0
        container_name: folders-api-server
        labels:
            product: 'folders'
            app: 'scan'
        environment:
            - SERVER_PORT=5056
            - OTEL_COLLECTOR_HOST=http://alloy:4318
            - OTEL_SERVICE_NAMESPACE=folders
            - OTEL_SERVICE_NAME=scan
            - OTEL_SERVICE_VERSION=1.0.0
        ports:
            - 5056:5056
        networks:
            - host-net

    alloy:
        image: grafana/alloy:latest
        volumes:
            - ./config.alloy:/etc/alloy/config.alloy
            - ./otel-collector-config.yaml:/etc/alloy/otel.yaml
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 12345:12345
        command:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
        networks:
            - host-net

    grafana:
        image: grafana/grafana-enterprise:latest
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        container_name: grafana
        restart: unless-stopped
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: password
            GF_FEATURE_TOGGLES_ENABLE: 'timeSeriesTable'
        volumes:
            - ./grafana-data:/var/lib/grafana
            - ./setup:/etc/grafana/provisioning
            - ./dashboards:/var/lib/grafana/dashboards
        ports:
            - 3000:3000
        networks:
            - host-net

    loki:
        image: grafana/loki:main
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        container_name: loki
        hostname: loki
        volumes:
            - ./loki-config.yaml:/etc/loki/local-config.yaml
        command: ['-config.file=/etc/loki/local-config.yaml', '-config.expand-env=true']
        networks:
            - host-net

    tempo:
        image: grafana/tempo:main-24cbe3e
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        container_name: tempo
        hostname: tempo
        #      command: [ "-config.file=/etc/tempo.yaml", "-multitenancy.enabled=true"]
        command: ['-config.file=/etc/tempo.yaml']
        volumes:
            - ./tempo.yml:/etc/tempo.yaml
            - ./tempo-data:/tmp/tempo
        networks:
            - host-net

    opensearch:
        image: opensearchproject/opensearch:2.8.0
        container_name: opensearch
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch
            - discovery.seed_hosts=opensearch
            - cluster.initial_master_nodes=opensearch
            - plugins.query.datasources.encryption.masterkey=b534b1ce4f4f04b524a2b500
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
            - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m' # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - ./opensearch-data:/usr/share/opensearch/data
        ports:
            - 9276:9200
            - 9277:9600 # required for Performance Analyzer
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        networks:
            - host-net

    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:2.8.0
        container_name: opensearch-dashboards
        ports:
            - 5601:5601
        expose:
            - '5601'
        environment:
            OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
        networks:
            - host-net

    prometheus:
        image: rapidfort/prometheus:latest
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - --web.enable-remote-write-receiver
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        networks:
            - host-net

    node-exporter:
        image: rapidfort/node-exporter:1.7-debian-11
        networks:
            - host-net
        ports:
            - 9100:9100

    vector:
        image: timberio/vector:nightly-2024-02-14-alpine
        volumes:
            - ./vector.yaml:/etc/vector/vector.yaml
        networks:
            - host-net

networks:
    host-net:
        external: true
