version: '3.7'

services:
    driver-app-1:
        image: driver-app:1.0.0
        build:
            context: ../driver-app
            dockerfile: Dockerfile
        container_name: driver-app-1
        labels:
            service_namespace: common_services
            service_name: driver-app-1
            logger: vector
        environment:
            - SERVER_PORT=5055
            - OTEL_COLLECTOR_HOST=http://alloy-common-services:4318
            - OTEL_RESOURCE_ATTRIBUTES=service.namespace=common_services
            - OTEL_SERVICE_NAME=driver-app-1
            - OTEL_SERVICE_VERSION=1.0.0
        ports:
            - 5055:5055
        networks:
            - host-net

    driver-app-2:
        build:
            context: ../driver-app-2
            dockerfile: Dockerfile
        image: driver-app-2:1.0.0
        container_name: driver-app-2
        labels:
            logger: vector
            service_namespace: common_services
            service_name: driver-app-2
        environment:
            - SERVER_PORT=5000
            - OTEL_SERVICE_NAME=driver-app-2
            - OTEL_SERVICE_VERSION=1.0.0
            - OTEL_RESOURCE_ATTRIBUTES=service.namespace=common_services
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy-common-services:4318
            - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
            - API_URL=http://driver-app-1:5055
        ports:
            - 5000:5000
        networks:
            - host-net

    driver-app-2-fastapi:
        build:
            context: ../fastapi-app
            dockerfile: Dockerfile
        image: driver-app-2-fastapi:1.0.0
        container_name: driver-app-2-fastapi
        labels:
            logger: vector
            service_namespace: 'nautilus'
            service_name: 'driver-app-2-fastapi'
        environment:
            - OTEL_SERVICE_NAME=driver-app-2-fastapi
            - OTEL_RESOURCE_ATTRIBUTES=service.namespace=nautilus
            - OTEL_SERVICE_VERSION=1.0.0
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_METRICS_EXPORTER=otlp
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy-nautilus:4318
            - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
            - OTEL_PYTHON_LOG_CORRELATION=true
            - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
            - API_URL=http://driver-app-1:5055
        ports:
            - 8000:8000
        networks:
            - host-net

    alloy-nautilus:
        image: grafana/alloy:latest
        volumes:
            - ./config.alloy:/etc/alloy/config.alloy
        command:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
        networks:
            - host-net
        environment:
            - OTEL_SERVICE_NAMESPACE=nautilus

    alloy-common-services:
        image: grafana/alloy:latest
        volumes:
            - ./config.alloy:/etc/alloy/config.alloy
        command:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
        networks:
            - host-net
        environment:
            - OTEL_SERVICE_NAMESPACE=common_services

    grafana:
        image: grafana/grafana-enterprise:latest
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        container_name: grafana
        restart: unless-stopped
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: password
            GF_FEATURE_TOGGLES_ENABLE: 'timeSeriesTable'
        volumes:
            - ./grafana-data:/var/lib/grafana
            - ./setup:/etc/grafana/provisioning
            - ./dashboards:/var/lib/grafana/dashboards
        ports:
            - 3000:3000
        networks:
            - host-net

    loki:
        image: grafana/loki:main
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        container_name: loki
        hostname: loki
        volumes:
            - ./loki-config.yaml:/etc/loki/local-config.yaml
        command: ['-config.file=/etc/loki/local-config.yaml', '-config.expand-env=true']
        networks:
            - host-net

    tempo:
        image: grafana/tempo:main-24cbe3e
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        container_name: tempo
        hostname: tempo
        #      command: [ "-config.file=/etc/tempo.yaml", "-multitenancy.enabled=true"]
        command: ['-config.file=/etc/tempo.yaml']
        volumes:
            - ./tempo.yml:/etc/tempo.yaml
            - ./tempo-data:/tmp/tempo
        networks:
            - host-net

    opensearch:
        image: opensearchproject/opensearch:2.8.0
        container_name: opensearch
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch
            - discovery.seed_hosts=opensearch
            - cluster.initial_master_nodes=opensearch
            - plugins.query.datasources.encryption.masterkey=b534b1ce4f4f04b524a2b500
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
            - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m' # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - ./opensearch-data:/usr/share/opensearch/data
        ports:
            - 9276:9200
            - 9277:9600 # required for Performance Analyzer
        labels:
            logging: 'promtail_sys'
            tenant_id: 'admin'
        networks:
            - host-net
        command:
            - /bin/bash
            - -c
            - |
                ./bin/opensearch-plugin install https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/releases/download/2.8.0.0/prometheus-exporter-2.8.0.0.zip &&
                /usr/share/opensearch/opensearch-docker-entrypoint.sh opensearch

    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:2.8.0
        container_name: opensearch-dashboards
        ports:
            - 5601:5601
        expose:
            - '5601'
        environment:
            OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
        networks:
            - host-net

    node-exporter:
        image: rapidfort/node-exporter:1.7-debian-11
        networks:
            - host-net
        ports:
            - 9100:9100

    vector:
        image: timberio/vector:nightly-2024-02-14-alpine
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./vector.yaml:/etc/vector/vector.yaml
        networks:
            - host-net

    mimir:
        image: grafana/mimir:latest
        volumes:
          - ./mimir.yaml:/etc/mimir/config.yaml
        command: ["--config.file", "/etc/mimir/config.yaml"]
        networks:
            - host-net

    alloy-metrics-scraper:
        image: grafana/alloy:latest
        volumes:
            - ./metrics-scraper-config.alloy:/etc/alloy/config.alloy
        command:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
        networks:
            - host-net
        environment:
            - OTEL_SERVICE_NAMESPACE=nautilus
    
networks:
    host-net:
        external: true
