{
 "title": "Docker Monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(machine_memory_bytes,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Docker Swarm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(machine_memory_bytes{job=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swarm CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_user_seconds_total{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"}[2m])) / sum (machine_cpu_cores{job=\"$cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Swarm Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"}) / sum(machine_memory_bytes{job=\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Container Resource Allocation and Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(rate(container_cpu_user_seconds_total{image!=\"\", image!~\".*cadvisor\", image!=\"\", job=\"$cluster\"}[2m]), \"node\", \"$1\", \"instance\", \"(.*):48080\")\r\n\r"
    },
    {
     "expr": "container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\", image!=\"\", job=\"$cluster\"}"
    },
    {
     "expr": "((container_spec_memory_limit_bytes{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"} == 0) + on (instance) group_left(image) (machine_memory_bytes{job=\"$cluster\"})) OR (container_spec_memory_limit_bytes{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"} > 0)"
    },
    {
     "expr": "time() - container_start_time_seconds{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(rate(container_cpu_user_seconds_total{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"}[2m]) * 100, \"node\", \"$1\", \"instance\", \"(.*):48080\")",
     "legendFormat": "{{node}} - {{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(container_memory_working_set_bytes{image!=\"\", image!~\".*cadvisor\", image!=\"\", job=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*):48080\")",
     "legendFormat": "{{node}} - {{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\", image!~\".*cadvisor\", job=\"$cluster\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}