version: "3.7"

services:
  api-server-2a:
    image: driver-app:1.0.0
    container_name: api-server-2a
    labels:
      logging: "promtail_app"
      tenant_id: "api-server-2"
      service_namespace: "api-server-2"
      service_name: "api-server-2a"
    environment:
      - OTEL_COLLECTOR_HOST=http://otel_collector_2:4318
      - OTEL_SERVICE_NAMESPACE=api-server-2
      - OTEL_SERVICE_NAME=api-server-2a
      - OTEL_SERVICE_VERSION=1.0.0
      - SERVER_PORT=5055
    ports:
      - 5055:5055
    networks:
      - host-net

  otel_collector_2:
    image: otel/opentelemetry-collector-contrib:latest
    labels:
      logging: "promtail_sys"
      tenant_id: "admin"
    hostname: otel_collector_2
    container_name: otel_collector_2
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./otel-collector-config.yaml:/conf/config.yaml
    restart: on-failure
    networks:
      - host-net

networks:
  host-net:
    external: true
