---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  logger: vector
  service_namespace: common_services
  service_name: driver-app-2

configMapGenerator:
  - name: driver-app-2
    literals:
      - SERVER_PORT=5000
      - OTEL_SERVICE_NAME=driver-app-2
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=common_services
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://common-svc-alloy.monitoring.svc.cluster.local:4318
      - OTEL_NODE_RESOURCE_DETECTORS=all
      - API_URL=http://driver-app-1:5055

resources:
  - ./deployment.yaml
  - ./service.yaml
